CAV-30: fix pipeline-3

diff --git a/.github/workflows/github-ci.yml b/.github/workflows/github-ci.yml
--- a/.github/workflows/github-ci.yml
+++ b/.github/workflows/github-ci.yml
@@ -15,4 +15,9 @@ jobs:
       - name: Run tests
         run: |
           ./run-test.sh
-        
+          
+          test_status=$?
+          if [ $test_status -ne 0 ]; then
+            echo "Tests failed. Exiting with status $test_status."
+            exit $test_status
+          fi
